services:
  - type: web
    name: listener
    env: node
    buildCommand: "npm install"
    startCommand: "bash start.sh"
    plan: free
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: fastapi-processor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python listener.py"
    plan: free
    envVars:
      - key: PORT
        value: 10001
